/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Dialog from '../packages/dialog/index.js';
import MessageBox from '../packages/message-box/index.js';

const components = [
  Dialog,
  Button
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;

  components.map(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

module.exports = {
  version: '2.0.7',
  Dialog,
  Button,
  MessageBox
};

module.exports.default = module.exports;
